 // Calendar export utilities for iCal and Google Calendar
 import { createEvents, EventAttributes } from 'ics';
 import { DutyAnalysis } from '@/types/fatigue';
 import { format, parseISO } from 'date-fns';
 
 /**
  * Generate ICS file content for duties
  */
 export function generateIcsContent(duties: DutyAnalysis[]): Promise<string> {
   return new Promise((resolve, reject) => {
     const events: EventAttributes[] = duties.map(duty => {
       const dateStr = duty.dateString || format(duty.date, 'yyyy-MM-dd');
       const [year, month, day] = dateStr.split('-').map(Number);
       
       // Parse report and release times
       const reportTime = duty.reportTimeLocal || '06:00';
       const releaseTime = duty.releaseTimeLocal || '18:00';
       const [reportH, reportM] = reportTime.split(':').map(Number);
       const [releaseH, releaseM] = releaseTime.split(':').map(Number);
       
       // Build flight route description
       const route = duty.flightSegments.map(seg => 
         `${seg.flightNumber}: ${seg.departure} → ${seg.arrival} (${seg.departureTime}-${seg.arrivalTime})`
       ).join('\n');
       
       // Risk color for description
       const riskEmoji = {
         'LOW': '🟢',
         'MODERATE': '🟡',
         'HIGH': '🟠',
         'CRITICAL': '🔴'
       }[duty.overallRisk] || '⚪';
       
       return {
         start: [year, month, day, reportH, reportM] as [number, number, number, number, number],
         end: [year, month, day, releaseH, releaseM] as [number, number, number, number, number],
         title: `✈️ ${duty.flightSegments.map(s => s.flightNumber).join(' • ') || 'Flight Duty'}`,
         description: [
           `${riskEmoji} Risk Level: ${duty.overallRisk}`,
           `Performance: ${Math.round(duty.avgPerformance)}% avg, ${Math.round(duty.minPerformance)}% min`,
           `Sectors: ${duty.sectors}`,
           `Block Hours: ${duty.blockHours.toFixed(1)}h`,
           `Duty Hours: ${duty.dutyHours.toFixed(1)}h`,
           '',
           'Flight Schedule:',
           route,
           '',
           'Generated by Aerowake'
         ].join('\n'),
         location: duty.flightSegments.length > 0 
           ? `${duty.flightSegments[0].departure} → ${duty.flightSegments[duty.flightSegments.length - 1].arrival}`
           : undefined,
         categories: ['Flight Duty', duty.overallRisk],
         status: 'CONFIRMED' as const,
         busyStatus: 'BUSY' as const,
         productId: 'Aerowake/Fatigue-Analysis',
         uid: duty.dutyId || `duty-${dateStr}-${Date.now()}`,
       };
     });
 
     createEvents(events, (error, value) => {
       if (error) {
         reject(error);
       } else {
         resolve(value);
       }
     });
   });
 }
 
 /**
  * Download ICS file (Apple Calendar compatible)
  */
 export async function downloadIcsFile(duties: DutyAnalysis[], filename: string = 'aerowake-roster.ics'): Promise<void> {
   try {
     const icsContent = await generateIcsContent(duties);
     const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8' });
     const url = URL.createObjectURL(blob);
     
     const anchor = document.createElement('a');
     anchor.href = url;
     anchor.download = filename;
     document.body.appendChild(anchor);
     anchor.click();
     document.body.removeChild(anchor);
     URL.revokeObjectURL(url);
   } catch (error) {
     console.error('Failed to generate ICS file:', error);
     throw error;
   }
 }
 
 /**
  * Generate Google Calendar URL for a single duty
  */
 export function generateGoogleCalendarUrl(duty: DutyAnalysis): string {
   const dateStr = duty.dateString || format(duty.date, 'yyyy-MM-dd');
   const reportTime = duty.reportTimeLocal || '06:00';
   const releaseTime = duty.releaseTimeLocal || '18:00';
   
   // Format: YYYYMMDDTHHMMSS
   const startDate = `${dateStr.replace(/-/g, '')}T${reportTime.replace(':', '')}00`;
   const endDate = `${dateStr.replace(/-/g, '')}T${releaseTime.replace(':', '')}00`;
   
   const title = `✈️ ${duty.flightSegments.map(s => s.flightNumber).join(' • ') || 'Flight Duty'}`;
   
   const route = duty.flightSegments.map(seg => 
     `${seg.flightNumber}: ${seg.departure} → ${seg.arrival}`
   ).join(', ');
   
   const details = [
     `Risk: ${duty.overallRisk}`,
     `Performance: ${Math.round(duty.avgPerformance)}%`,
     `Route: ${route}`,
     'Generated by Aerowake'
   ].join('\n');
   
   const location = duty.flightSegments.length > 0 
     ? `${duty.flightSegments[0].departure} - ${duty.flightSegments[duty.flightSegments.length - 1].arrival}`
     : '';
   
   const params = new URLSearchParams({
     action: 'TEMPLATE',
     text: title,
     dates: `${startDate}/${endDate}`,
     details: details,
     location: location,
   });
   
   return `https://calendar.google.com/calendar/render?${params.toString()}`;
 }
 
 /**
  * Open Google Calendar with all duties (creates multiple tabs or shows instructions)
  */
 export function openGoogleCalendarBatch(duties: DutyAnalysis[]): void {
   if (duties.length === 0) return;
   
   if (duties.length === 1) {
     window.open(generateGoogleCalendarUrl(duties[0]), '_blank');
     return;
   }
   
   // For multiple events, we need to open each in a new tab
   // Browsers may block multiple popups, so we'll open the first and provide instructions
   const firstUrl = generateGoogleCalendarUrl(duties[0]);
   window.open(firstUrl, '_blank');
   
   // Show an alert with instructions for bulk import
   alert(
     `Google Calendar doesn't support bulk import via URL.\n\n` +
     `For multiple events:\n` +
     `1. Download the iCal (.ics) file\n` +
     `2. Go to calendar.google.com\n` +
     `3. Click Settings (gear icon) → Import & export\n` +
     `4. Select the downloaded .ics file\n\n` +
     `The first event has been opened in a new tab.`
   );
 }